prec_dict = \
{
  "hydrated aluminum oxide": {"class(es)": ["Al"], "common name": "Al2O3", "id": 1},
  "BaCl2*2H2O": {"class(es)": ["Ba"], "common name": "BaCl2", "id": 2},
  "aluminum chloride": {"class(es)": ["Al"], "common name": "AlCl3", "id": 3},
  "cab-o-sil EH5a": {"class(es)": ["Si"], "common name": "fumed silica", "id": 4},
  "V2O5": {"class(es)": ["V"], "common name": "vanadium(V) oxide", "id": 5},
  "PTMS": {"class(es)": ["Si"], "common name": "phenyltrimethoxysilane", "id": 6},
  "sodium aluminum oxide": {"class(es)": ["Al", "Na"], "common name": "sodium aluminate", "id": 7},
  "IPA": {"class(es)": ["None"], "common name": "isopropyl alcohol", "id": 8},
  "HNO3": {"class(es)": ["None"], "common name": "nitric acid", "id": 9},
  "magnesium(II) acetate tetrahydrate": {"class(es)": ["Mg"], "common name": "magnesium acetate tetrahydrate", "id": 10},
  "Al(OH)3*H2O": {"class(es)": ["Al", "OH"], "common name": "aluminum hydroxide", "id": 11},
  "aluminium sulfate": {"class(es)": ["Al"], "common name": "aluminum sulfate", "id": 12},
  "Na2B4O7*10H2O": {"class(es)": ["B", "Na"], "common name": "sodium tetraborate decahydrate", "id": 13},
  "gallium oxide": {"class(es)": ["Ga"], "common name": "gallium(III) oxide", "id": 14},
  "manganese acetate": {"class(es)": ["Mg"], "common name": "manganese(II) acetate", "id": 15},
  "methyltriethoxysilane": {"class(es)": ["Si"], "common name": "methyltriethoxysilane", "id": 16},
  "HSZ-360": {"class(es)": ["Si", "Al"], "common name": "zeolite", "id": 17},
  "potassium gallate": {"class(es)": ["K", "Ga"], "common name": "potassium gallate", "id": 18},
  "oxalic acid dihydrate": {"class(es)": ["None"], "common name": "oxalic acid dihydrate", "id": 19},
  "aluminum sec-butoxide": {"class(es)": ["Al"], "common name": "aluminum sec-butoxide", "id": 20},
  "alumina powder": {"class(es)": ["Al"], "common name": "Al2O3", "id": 21},
  "Kieselsol": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 22},
  "cecasol-40": {"class(es)": ["Si"], "common name": "silica sol", "id": 23},
  "Zeolite Beta": {"class(es)": ["Si", "Al"], "common name": "zeolite Beta", "id": 24},
  "AS-40": {"class(es)": ["Si"], "common name": "amorphous silica", "id": 25},
  "Al(Oet)3": {"class(es)": ["Al"], "common name": "aluminum ethoxide", "id": 26},
  "2-propanol": {"class(es)": ["None"], "common name": "isopropanol", "id": 27},
  "tungstophosphoric acid": {"class(es)": ["W"], "common name": "tungstophosphoric acid", "id": 28},
  "sodium aluminate oxide": {"class(es)": ["Al", "Na"], "common name": "sodium aluminate", "id": 29},
  "aluminum isoproxide": {"class(es)": ["Al"], "common name": "aluminum isopropoxide", "id": 30},
  "Ca(NO3)2*4H2O": {"class(es)": ["Ca"], "common name": "calcium nitrate tetrahydrate", "id": 31},
  "dichlorodimethylsilane": {"class(es)": ["Si"], "common name": "dichlorodimethylsilane", "id": 32},
  "aluminum metal foil": {"class(es)": ["Al"], "common name": "aluminum", "id": 33},
  "MgO": {"class(es)": ["Mg"], "common name": "magnesium oxide", "id": 34},
  "NH4-linde A": {"class(es)": ["None"], "common name": "ammonium-exchanged Linde type A zeolite", "id": 35},
  "hydrated alumina": {"class(es)": ["Al"], "common name": "aluminum hydroxide", "id": 36},
  "Tin(IV) chloride": {"class(es)": ["Sn"], "common name": "tin(IV) chloride", "id": 37},
  "Na aluminate": {"class(es)": ["Al", "Na"], "common name": "sodium aluminate", "id": 38},
  "KNO3": {"class(es)": ["K"], "common name": "potassium nitrate", "id": 39},
  "KCl": {"class(es)": ["K"], "common name": "potassium chloride", "id": 40},
  "aluminum ribbon": {"class(es)": ["Al"], "common name": "aluminum", "id": 41},
  "vanadium oxide": {"class(es)": ["V"], "common name": "vanadium(V) oxide", "id": 42},
  "ferric sulfate": {"class(es)": ["Fe"], "common name": "iron(III) sulfate", "id": 43},
  "ethylene glycol monomethyl ether": {"class(es)": ["None"], "common name": "2-methoxyethanol", "id": 44},
  "isopropyl alcohol": {"class(es)": ["None"], "common name": "isopropanol", "id": 45},
  "AIP": {"class(es)": ["Al"], "common name": "aluminum isopropoxide", "id": 46},
  "Ga2O3": {"class(es)": ["Ga"], "common name": "gallium(III) oxide", "id": 47},
  "K3Fe(CN)6": {"class(es)": ["K", "Fe"], "common name": "potassium hexacyanoferrate(III)", "id": 48},
  "zinc oxide powder": {"class(es)": ["Zn"], "common name": "zinc oxide", "id": 49},
  "Ca(NO3)2": {"class(es)": ["Ca"], "common name": "calcium nitrate", "id": 50},
  "CBV500": {"class(es)": ["Si", "Al"], "common name": "zeolite", "id": 51},
  "vanadyl sulfate": {"class(es)": ["V"], "common name": "vanadyl sulfate", "id": 52},
  "Ultrasil": {"class(es)": ["Si"], "common name": "silicon dioxide", "id": 53},
  "H2O2": {"class(es)": ["None"], "common name": "hydrogen peroxide", "id": 54},
  "manganese(II) acetate": {"class(es)": ["Mg"], "common name": "manganese(II) acetate", "id": 55},
  "(CH3O)4Si": {"class(es)": ["Si"], "common name": "tetramethyl orthosilicate", "id": 56},
  "H-Y": {"class(es)": ["Si", "Al"], "common name": "zeolite HY", "id": 57},
  "ZrOCl2": {"class(es)": ["Zr"], "common name": "zirconium(IV) oxychloride", "id": 58},
  "Na2WO4": {"class(es)": ["Na", "W"], "common name": "sodium tungstate", "id": 59},
  "tin(II) chloride dehydrate": {"class(es)": ["Sn"], "common name": "tin(II) chloride dihydrate", "id": 60},
  "y-Al2O3": {"class(es)": ["Al"], "common name": "gamma-alumina", "id": 61},
  "pseudoboehmite": {"class(es)": ["Al"], "common name": "pseudoboehmite", "id": 62},
  "Cu(NO3)2": {"class(es)": ["Cu"], "common name": "copper(II) nitrate", "id": 63},
  "Co(CH3COO)2*4H2O": {"class(es)": ["Co"], "common name": "cobalt(II) acetate tetrahydrate", "id": 64},
  "Ti(SO4)2": {"class(es)": ["Ti"], "common name": "titanium(IV) sulfate", "id": 65},
  "Cab-O-Sil": {"class(es)": ["Si"], "common name": "fumed silica", "id": 66},
  "silicasol": {"class(es)": ["Si"], "common name": "silica sol", "id": 67},
  "Aluminum triisopropylate": {"class(es)": ["Al"], "common name": "aluminum isopropoxide", "id": 68},
  "CBV100": {"class(es)": ["Si", "Al"], "common name": "zeolite", "id": 69},
  "Co(OH)2": {"class(es)": ["Co"], "common name": "cobalt(II) hydroxide", "id": 70},
  "Reheis F -2000": {"class(es)": ["Al"], "common name": "aluminum hydroxide", "id": 71},
  "gallium nitrate": {"class(es)": ["Ga"], "common name": "gallium(III) nitrate", "id": 72},
  "MgHPO4": {"class(es)": ["Mg"], "common name": "magnesium hydrogen phosphate", "id": 73},
  "dysprosium nitrate": {"class(es)": ["Dy"], "common name": "dysprosium(III) nitrate", "id": 74},
  "tin(IV) chloride": {"class(es)": ["Sn"], "common name": "tin(IV) chloride", "id": 75},
  "aluminum nitrate nonahydrate": {"class(es)": ["Al"], "common name": "aluminum nitrate nonahydrate", "id": 76},
  # "Y zeolite HSZ-390HUA": {"class(es)": ["Si", "Al"], "common name": "Y zeolite", "id": 77},
  "silica powder": {"class(es)": ["Si"], "common name": "silicon dioxide", "id": 78},
  "zinc sulphate": {"class(es)": ["Zn"], "common name": "zinc sulfate", "id": 79},
  "lithium chloride": {"class(es)": ["None"], "common name": "lithium chloride", "id": 80},
  "zeolite T": {"class(es)": ["Si", "Al"], "common name": "zeolite T", "id": 81},
  "Aluminium hydroxide": {"class(es)": ["Al"], "common name": "aluminum hydroxide", "id": 82},
  "FeCl3": {"class(es)": ["Fe"], "common name": "iron(III) chloride", "id": 83},
  "aluminum powder": {"class(es)": ["Al"], "common name": "aluminum", "id": 84},
  "TiCl3": {"class(es)": ["Ti"], "common name": "titanium(III) chloride", "id": 85},
  "H2SO4": {"class(es)": ["None"], "common name": "sulfuric acid", "id": 86},
  "glass powder residues": {"class(es)": ["Si"], "common name": "silica (as a component of glass)", "id": 87},
  "cabosil m5": {"class(es)": ["Si"], "common name": "fumed silica", "id": 88},
  "germanium(IV) ethoxide": {"class(es)": ["Ge"], "common name": "germanium ethoxide", "id": 89},
  "sodium metaluminate": {"class(es)": ["Al", "Na"], "common name": "sodium aluminate", "id": 90},
  "LZY-62": {"class(es)": ["Si", "Al"], "common name": "zeolite", "id": 91},
  "aluminum-tri-isopropoxide": {"class(es)": ["Al"], "common name": "aluminum isopropoxide", "id": 92},
  "Al(iPrO)3": {"class(es)": ["Al"], "common name": "aluminum isopropoxide", "id": 93},
  "Ludox SM30": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 94},
  "tetraethylorthosilicate": {"class(es)": ["Si"], "common name": "tetraethyl orthosilicate", "id": 95},
  "Ludox-AS": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 96},
  "pyridine": {"class(es)": ["None"], "common name": "pyridine", "id": 97},
  "colloidal silica": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 98},
  "As2O5": {"class(es)": ["As"], "common name": "arsenic pentoxide", "id": 99},
  "beta": {"class(es)": ["Si", "Al"], "common name": "zeolite Beta", "id": 100},
  "Co(CH3COO)2": {"class(es)": ["Co"], "common name": "cobalt(II) acetate", "id": 101},
  "Snowtex ST-40": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 102},
  "Ludox LS-30": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 103},
  "fumed silicon dioxide": {"class(es)": ["Si"], "common name": "fumed silica", "id": 104},
  "Zn(CH3COO)2*4H2O": {"class(es)": ["Zn"], "common name": "zinc acetate tetrahydrate", "id": 105},
  "Aerosil 300": {"class(es)": ["Si"], "common name": "fumed silica", "id": 106},
  "powdered SiO2": {"class(es)": ["Si"], "common name": "silicon dioxide", "id": 107},
  "boehmite": {"class(es)": ["Al"], "common name": "boehmite", "id": 108},
  "Zr(IV)isopropoxide": {"class(es)": ["Zr"], "common name": "zirconium isopropoxide", "id": 109},
  "Ludox CL-X": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 110},
  "MnSO4": {"class(es)": ["Mn"], "common name": "manganese(II) sulfate", "id": 111},
  "H3PO4": {"class(es)": ["None"], "common name": "phosphoric acid", "id": 112},
  "NH4Cl": {"class(es)": ["None"], "common name": "ammonium chloride", "id": 113},
  "aluminum triisopropanolate": {"class(es)": ["Al"], "common name": "aluminum isopropoxide", "id": 114},
  "hydrous oxide": {"class(es)": ["None"], "common name": "unknown", "id": 115},
  "copper(II) acetate": {"class(es)": ["Cu"], "common name": "copper(II) acetate", "id": 116},
  "propyltriethoxy silane": {"class(es)": ["Si"], "common name": "propyltriethoxysilane", "id": 117},
  "AlOOH": {"class(es)": ["Al"], "common name": "aluminium oxyhydroxide", "id": 118},
  "Snowtex-ZL": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 119},
  "ammonium fluoride": {"class(es)": ["F"], "common name": "ammonium fluoride", "id": 120},
  "zinc nitrate hexahydrate": {"class(es)": ["Zn"], "common name": "zinc nitrate hexahydrate", "id": 121},
  "Al(NO)3": {"class(es)": ["Al"], "common name": "aluminum nitrate", "id": 122},
  "cobalt carbonate hydrate": {"class(es)": ["Co"], "common name": "cobalt(II) carbonate hydrate", "id": 123},
  "OS-12": {"class(es)": ["None"], "common name": "zeolite", "id": 124},
  "Ludox": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 125},
  "gallium sulfate": {"class(es)": ["Ga"], "common name": "gallium(II) sulfate", "id": 126},
  "Al(OiPr)3": {"class(es)": ["Al"], "common name": "aluminum isopropoxide", "id": 127},
  "acetone": {"class(es)": ["None"], "common name": "acetone", "id": 128},
  "Ludox 40": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 129},
  "SiO2": {"class(es)": ["Si"], "common name": "silicon dioxide", "id": 130},
  "Catapal A alumina": {"class(es)": ["Al"], "common name": "gamma-alumina", "id": 131},
  "ASA": {"class(es)": ["None"], "common name": "zeolite", "id": 132},
  "gallium oxyhydroxide": {"class(es)": ["Ga"], "common name": "gallium oxyhydroxide", "id": 133},
  "tri-isopropylate aluminum": {"class(es)": ["Al"], "common name": "aluminum isopropoxide", "id": 134},
  "Mg(NO3)2": {"class(es)": ["Mg"], "common name": "magnesium nitrate", "id": 135},
  "sodium aluminates": {"class(es)": ["Al", "Na"], "common name": "sodium aluminate", "id": 136},
  "diphosphoric acid": {"class(es)": ["None"], "common name": "pyrophosphoric acid", "id": 137},
  "SN-40": {"class(es)": ["Si"], "common name": "silica sol", "id": 138},
  "Na2Al2O4": {"class(es)": ["Al", "Na"], "common name": "sodium aluminate", "id": 139},
  "zinc acetate dehydrate": {"class(es)": ["Zn"], "common name": "zinc acetate dihydrate", "id": 140},
  "To(Obut)4": {"class(es)": ["None"], "common name": "tetrabutyl orthotitanate", "id": 141},
  "LZY-210 Y": {"class(es)": ["Si", "Al"], "common name": "zeolite LZY-210", "id": 142},
  "tetraethyl orthosilicate": {"class(es)": ["Si"], "common name": "tetraethyl orthosilicate", "id": 143},
  "208 pseudoboehmite alumina": {"class(es)": ["Al"], "common name": "pseudoboehmite", "id": 144},
  "Silica acid": {"class(es)": ["Si"], "common name": "silicic acid", "id": 145},
  "iron(III) sulfate": {"class(es)": ["Fe"], "common name": "iron(III) sulfate", "id": 146},
  "dimethylformamide": {"class(es)": ["None"], "common name": "N,N-dimethylformamide", "id": 147},
  "vanadium(IV) acetate": {"class(es)": ["V"], "common name": "vanadium(IV) acetate", "id": 148},
  "i-BuOH": {"class(es)": ["None"], "common name": "isobutanol", "id": 149},
  "aluminum sulphate": {"class(es)": ["Al"], "common name": "aluminum sulfate", "id": 150},
  "HF": {"class(es)": ["F"], "common name": "hydrofluoric acid", "id": 151},
  "Zeosil 1165": {"class(es)": ["Si"], "common name": "silica gel", "id": 152},
  "Magnesium acetate": {"class(es)": ["Mg"], "common name": "magnesium acetate", "id": 153},
  "VOSO4": {"class(es)": ["V"], "common name": "vanadyl sulfate", "id": 154},
  "tetraethyoxysilane": {"class(es)": ["Si"], "common name": "tetraethyl orthosilicate", "id": 155},
  "Al2O3*1.9H2O": {"class(es)": ["Al"], "common name": "hydrated alumina", "id": 156},
  "Ludox colloidal silica": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 157},
  "Ludox HS30": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 158},
  "Ludox LS30": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 159},
  "L-lysine": {"class(es)": ["None"], "common name": "L-lysine", "id": 160},
  "aluminum nitrate hydrate": {"class(es)": ["Al"], "common name": "aluminum nitrate hydrate", "id": 161},
  "Catapal B": {"class(es)": ["Al"], "common name": "alpha-alumina", "id": 162},
  "RbOH": {"class(es)": ["OH", "Rb"], "common name": "rubidium hydroxide", "id": 163},
  "Aerosil": {"class(es)": ["Si"], "common name": "fumed silica", "id": 164},
  "Al(sOBu)3": {"class(es)": ["Al"], "common name": "aluminum sec-butoxide", "id": 165},
  "Tween 20": {"class(es)": ["None"], "common name": "polysorbate 20", "id": 166},
  "Powder Al": {"class(es)": ["Al"], "common name": "aluminum powder", "id": 167},
  "CoCl2": {"class(es)": ["Co"], "common name": "cobalt(II) chloride", "id": 168},
  "Aerosil 130 V": {"class(es)": ["Si"], "common name": "fumed silica", "id": 169},
  "ammonium hydroxide": {"class(es)": ["None"], "common name": "ammonium hydroxide", "id": 170},
  "aluminum oxide": {"class(es)": ["Al"], "common name": "alumina", "id": 171},
  "320HOA": {"class(es)": ["Si", "Al"], "common name": "zeolite", "id": 172},
  "chromium nitrate nanohydrate": {"class(es)": ["Cr"], "common name": "chromium(III) nitrate nonahydrate", "id": 173},
  "chromium acetate": {"class(es)": ["Cr"], "common name": "chromium(III) acetate", "id": 174},
  "titanium(IV) butoxide": {"class(es)": ["Ti"], "common name": "titanium(IV) butoxide", "id": 175},
  "Cesium hydroxide": {"class(es)": ["Cs", "OH"], "common name": "cesium hydroxide", "id": 176},
  "AlPO4": {"class(es)": ["Al", "P"], "common name": "aluminum phosphate", "id": 177},
  "rice husk": {"class(es)": ["Si"], "common name": "silica (as a component)", "id": 178},
  "Al2SO4": {"class(es)": ["Al"], "common name": "aluminum sulfate", "id": 179},
  "cobalt acetate": {"class(es)": ["Co"], "common name": "cobalt(II) acetate", "id": 180},
  "Precipitated silica": {"class(es)": ["Si"], "common name": "precipitated silica", "id": 181},
  "niobium oxalate": {"class(es)": ["Nb"], "common name": "niobium oxalate", "id": 182},
  "Ludox PX-30": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 183},
  "levasil VP 4038": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 184},
  "Ludox As-40": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 185},
  "acetic acid": {"class(es)": ["None"], "common name": "acetic acid", "id": 186},
  "HUA 390": {"class(es)": ["Si", "Al"], "common name": "zeolite HUA-390", "id": 187},
  "Mn(NO3)2": {"class(es)": ["Mn"], "common name": "manganese(II) nitrate", "id": 188},
  "Nalco's 1SJ612": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 189},
  "Snowtex S": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 190},
  "PHAPTMS": {"class(es)": ["Si"], "common name": "phenyltriethoxysilane", "id": 191},
  "Ludox AS-40": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 192},
  "neodymium nitrate": {"class(es)": ["Nd"], "common name": "neodymium(III) nitrate", "id": 193},
  "germanium dioxide": {"class(es)": ["Ge"], "common name": "germanium dioxide", "id": 194},
  "VTES": {"class(es)": ["Si"], "common name": "vinyltriethoxysilane", "id": 195},
  "Co(NO3)2*6H2O": {"class(es)": ["Co"], "common name": "cobalt(II) nitrate hexahydrate", "id": 196},
  "Ludox As40": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 197},
  "RHA silica": {"class(es)": ["Si"], "common name": "rice husk ash silica", "id": 198},
  "aluminum-sec-butoxide": {"class(es)": ["Al"], "common name": "aluminum sec-butoxide", "id": 199},
  "quartz": {"class(es)": ["Si"], "common name": "quartz", "id": 200},
  "Al(NO3)3": {"class(es)": ["Al"], "common name": "aluminum nitrate", "id": 201},
  "aluminum isopropylate": {"class(es)": ["Al"], "common name": "aluminum isopropoxide", "id": 202},
  "silica thiols": {"class(es)": ["Si"], "common name": "thiol-functionalized silica", "id": 203},
  "LZY-52": {"class(es)": ["Si"], "common name": "zeolite LZY-52", "id": 204},
  "VO(SO4)*5H2O": {"class(es)": ["V"], "common name": "vanadyl sulfate pentahydrate", "id": 205},
  "colloidal silica NS-30": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 206},
  "copper(II) sulfate": {"class(es)": ["Cu"], "common name": "copper(II) sulfate", "id": 207},
  "magnesium acetate tetrahydrate": {"class(es)": ["Mg"], "common name": "magnesium acetate tetrahydrate", "id": 208},
  "HSZ-360HUA": {"class(es)": ["Si", "Al"], "common name": "zeolite HSZ-360HUA", "id": 209},
  "wet silica": {"class(es)": ["Si"], "common name": "hydrated silica", "id": 210},
  "H2SiO3": {"class(es)": ["Si"], "common name": "silicic acid", "id": 211},
  "titanium diisopropoxide(bis)acetylacetonate": {"class(es)": ["Ti"], "common name": "titanium diisopropoxide bis(acetylacetonate)", "id": 212},
  "diatomite": {"class(es)": ["Si", "Al"], "common name": "diatomaceous earth", "id": 213},
  "samarium nitrate": {"class(es)": ["Sm"], "common name": "samarium(III) nitrate", "id": 214},
  "zeolite beta": {"class(es)": ["Si", "Al"], "common name": "zeolite Beta", "id": 215},
  "aluminum triisopropylate": {"class(es)": ["Al"], "common name": "aluminum isopropoxide", "id": 216},
  "Na2SiO3": {"class(es)": ["Si", "Na"], "common name": "sodium silicate", "id": 217},
  "Ti(OiPr)4": {"class(es)": ["Ti"], "common name": "titanium isopropoxide", "id": 218},
  "Mg(Oac)2": {"class(es)": ["Mg"], "common name": "magnesium acetate", "id": 219},
  "cobalt(II) acetate tetrahydrate": {"class(es)": ["Co"], "common name": "cobalt(II) acetate tetrahydrate", "id": 220},
  "carbon black": {"class(es)": ["None"], "common name": "carbon black", "id": 221},
  "CBV-720": {"class(es)": ["Si", "Al"], "common name": "zeolite CBV-720", "id": 222},
  "aluminum-trisec-butoxide": {"class(es)": ["Al"], "common name": "aluminum sec-butoxide", "id": 223},
  "H-kanemite": {"class(es)": ["Si", "Na"], "common name": "kanemite", "id": 224},
  "copper nitrate": {"class(es)": ["Cu"], "common name": "copper(II) nitrate", "id": 225},
  "Boric acid": {"class(es)": ["B"], "common name": "boric acid", "id": 226},
  "Fe(NO3)3": {"class(es)": ["Fe"], "common name": "iron(III) nitrate", "id": 227},
  "Ludox SM colloidal silica": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 228},
  "aluminum triethoxide": {"class(es)": ["Al"], "common name": "aluminum ethoxide", "id": 229},
  "Ludox": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 230},
  "aluminum sulfate": {"class(es)": ["Al"], "common name": "aluminum sulfate", "id": 231},
  "HGaCl4": {"class(es)": ["Ga"], "common name": "gallium(III) chloride", "id": 232},
  "VOSO4*5H2O": {"class(es)": ["V"], "common name": "vanadyl sulfate pentahydrate", "id": 233},
  "Rice husk ash": {"class(es)": ["Si"], "common name": "silica (as a component)", "id": 234},
  "Mn(CH3COO)2": {"class(es)": ["Mn"], "common name": "manganese(II) acetate", "id": 235},
  "Co(OAc)2*4H2O": {"class(es)": ["Co"], "common name": "cobalt(II) acetate tetrahydrate", "id": 236},
  "CoSO4": {"class(es)": ["Co"], "common name": "cobalt(II) sulfate", "id": 237},
  "Ludox TMA": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 238},
  "methanol": {"class(es)": ["None"], "common name": "methanol", "id": 239},
  "aluminum hydroxyacetate": {"class(es)": ["Al"], "common name": "aluminum hydroxyacetate", "id": 240},
  "alumina-silica microspheres": {"class(es)": ["Si", "Al"], "common name": "alumina-silica microspheres", "id": 241},
  "lithium hydroxide": {"class(es)": ["Li", "OH"], "common name": "lithium hydroxide", "id": 242},
  "Ultrasil VN3SP": {"class(es)": ["Si"], "common name": "precipitated silica", "id": 243},
  "copper(II) oxide": {"class(es)": ["Cu"], "common name": "copper(II) oxide", "id": 244},
  "Ludox S40": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 245},
  "Cabosil M5": {"class(es)": ["Si"], "common name": "fumed silica", "id": 246},
  "aluminium sulphate": {"class(es)": ["Al"], "common name": "aluminum sulfate", "id": 247},
  "Reheiss F-2000": {"class(es)": ["Al"], "common name": "aluminum hydroxide", "id": 248},
  "pseudo-g-AlO(OH)": {"class(es)": ["Al"], "common name": "pseudo-boehmite", "id": 249},
  "Mg3(PO4)2*8H2O": {"class(es)": ["Mg"], "common name": "magnesium phosphate octahydrate", "id": 250},
  "Silica gel": {"class(es)": ["Si"], "common name": "silica gel", "id": 251},
  "glycerol": {"class(es)": ["None"], "common name": "glycerol", "id": 252},
  "germanium ethoxide": {"class(es)": ["Ge"], "common name": "germanium ethoxide", "id": 253},
  "AlCl3*6H2O": {"class(es)": ["Al"], "common name": "aluminum chloride hexahydrate", "id": 254},
  "potassium hydroxide": {"class(es)": ["K", "OH"], "common name": "potassium hydroxide", "id": 255},
  "silicate sol": {"class(es)": ["Si", "Na"], "common name": "sodium silicate solution", "id": 256},
  "SrNO3": {"class(es)": ["Sr"], "common name": "strontium nitrate", "id": 257},
  "Aerodisp W6025": {"class(es)": ["Si"], "common name": "fumed silica dispersion", "id": 258},
  "Co(CH3CO2)2": {"class(es)": ["Co"], "common name": "cobalt(II) acetate", "id": 259},
  "manganese nitrate": {"class(es)": ["Mn"], "common name": "manganese(II) nitrate", "id": 260},
  "iron sulfate": {"class(es)": ["Fe"], "common name": "iron(II) sulfate", "id": 261},
  "acidic silica sol": {"class(es)": ["Si"], "common name": "acidic colloidal silica", "id": 262},
  "aluminum oxyhydroxide": {"class(es)": ["Al"], "common name": "aluminum oxyhydroxide", "id": 263},
  "Si(OCH3)4": {"class(es)": ["Si"], "common name": "tetramethyl orthosilicate", "id": 264},
  "CsF": {"class(es)": ["Cs", "F"], "common name": "cesium fluoride", "id": 265},
  "Co(NO3)2": {"class(es)": ["Co"], "common name": "cobalt(II) nitrate", "id": 266},
  "tetrabutylorthotitanate": {"class(es)": ["Ti"], "common name": "tetrabutyl titanate", "id": 267},
  "NH3": {"class(es)": ["None"], "common name": "ammonia", "id": 268},
  "iron(II) sulphate hepta-hydrate": {"class(es)": ["Fe"], "common name": "iron(II) sulfate heptahydrate", "id": 269},
  "CoCl2*6H2O": {"class(es)": ["Co"], "common name": "cobalt(II) chloride hexahydrate", "id": 270},
  "LZ-210": {"class(es)": ["Si", "Al"], "common name": "zeolite LZ-210", "id": 271},
  "Ni(CH3COO)2": {"class(es)": ["Ni"], "common name": "nickel(II) acetate", "id": 272},
  "silica fibers": {"class(es)": ["Si"], "common name": "silica fibers", "id": 273},
  "H3PO4": {"class(es)": ["P"], "common name": "phosphoric acid", "id": 274},
  "virtrosilicon": {"class(es)": ["Si"], "common name": "silica", "id": 275},
  "iron(II) chloride": {"class(es)": ["Fe"], "common name": "iron(II) chloride", "id": 276},
  "NH4-mordenite": {"class(es)": ["Si", "Al"], "common name": "ammonium mordenite", "id": 277},
  "sodium meta-aluminate": {"class(es)": ["Al", "Na"], "common name": "sodium meta-aluminate", "id": 278},
  "Al2(So4)3": {"class(es)": ["Al"], "common name": "aluminum sulfate", "id": 279},
  "Cobalt(II) nitrate hexahydrate": {"class(es)": ["Co"], "common name": "cobalt(II) nitrate hexahydrate", "id": 280},
  "tin(IV) chloride pentahydrate": {"class(es)": ["Ti"], "common name": "tin(IV) chloride pentahydrate", "id": 281},
  "SiO2 powder": {"class(es)": ["Si"], "common name": "silicon dioxide powder", "id": 282},
  "magnesium oxide": {"class(es)": ["Mg"], "common name": "magnesium oxide", "id": 283},
  "Al-isoproxide": {"class(es)": ["Al"], "common name": "aluminum isopropoxide", "id": 284},
  "aluminum hydroxide hydrate": {"class(es)": ["Al"], "common name": "aluminum hydroxide", "id": 285},
  "sodium bromide": {"class(es)": ["Na"], "common name": "sodium bromide", "id": 286},
  "phosphoric acid": {"class(es)": ["P"], "common name": "phosphoric acid", "id": 287},
  "Catapal": {"class(es)": ["Al"], "common name": "alpha-alumina", "id": 288},
  "bohmite alumina": {"class(es)": ["Al"], "common name": "boehmite", "id": 289},
  "amorphous silica": {"class(es)": ["Si"], "common name": "amorphous silica", "id": 290},
  "PHI": {"class(es)": ["Si", "Al", "K"], "common name": "unknown", "id": 291},
  "SN40": {"class(es)": ["Si"], "common name": "silica sol", "id": 292},
  "gallium metal": {"class(es)": ["Ga"], "common name": "gallium", "id": 293},
  "ammonium nitrate": {"class(es)": ["None"], "common name": "ammonium nitrate", "id": 294},
  "ammonium": {"class(es)": ["None"], "common name": "ammonium", "id": 295},
  "sodium silicate": {"class(es)": ["Si", "Na"], "common name": "sodium silicate", "id": 296},
  "Ludox AS40": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 297},
  "tetramethoxysilane": {"class(es)": ["Si"], "common name": "tetramethoxysilane", "id": 298},
  "aluminum tri-(sec-butoxide)": {"class(es)": ["Al"], "common name": "aluminum sec-butoxide", "id": 299},
  "MCM-41": {"class(es)": ["Si", "Al"], "common name": "MCM-41", "id": 300},
  "TIPO": {"class(es)": ["Ti", "P"], "common name": "titanium isopropoxide", "id": 301},
  "silica-alumina gel": {"class(es)": ["Si", "Al"], "common name": "silica-alumina gel", "id": 302},
  "FeSO4": {"class(es)": ["Fe"], "common name": "iron(II) sulfate", "id": 303},
  "gallium oxide hydroxide": {"class(es)": ["Ga"], "common name": "gallium hydroxide", "id": 304},
  "ferric chloride": {"class(es)": ["Fe"], "common name": "ferric chloride", "id": 305},
  "sodium aluminate": {"class(es)": ["Al", "Na"], "common name": "sodium aluminate", "id": 306},
  "orthophosphoric acid": {"class(es)": ["P"], "common name": "phosphoric acid", "id": 307},
  "Ludox AS-30": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 308},
  "HS-30": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 309},
  "silicalite": {"class(es)": ["Si"], "common name": "silicalite", "id": 310},
  "quartz sand": {"class(es)": ["Si"], "common name": "quartz sand", "id": 311},
  "Y zeolite": {"class(es)": ["Si", "Al"], "common name": "Y zeolite", "id": 312},
  "sodium chloride": {"class(es)": ["Na"], "common name": "sodium chloride", "id": 313},
  "coal fly ash": {"class(es)": ["Si", "Al"], "common name": "coal fly ash", "id": 314},
  "cabosil": {"class(es)": ["Si"], "common name": "fumed silica", "id": 315},
  "Co(acetate)": {"class(es)": ["Co"], "common name": "cobalt(II) acetate", "id": 316},
  "ferric nitrate": {"class(es)": ["Fe"], "common name": "ferric nitrate", "id": 317},
  "Aluminum isopropoxide": {"class(es)": ["Al"], "common name": "aluminum isopropoxide", "id": 318},
  "solid silica gel": {"class(es)": ["Si"], "common name": "solid silica gel", "id": 319},
  "KOH": {"class(es)": ["K", "OH"], "common name": "potassium hydroxide", "id": 320},
  "sulfuric acid": {"class(es)": ["None"], "common name": "sulfuric acid", "id": 321},
  "colloidal SiO2": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 322},
  "HS-40": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 323},
  "NH4-Y zeolite": {"class(es)": ["Si", "Al"], "common name": "ammonium Y zeolite", "id": 324},
  "silica colloidal gel": {"class(es)": ["Si"], "common name": "silica gel", "id": 325},
  "aluminum trihydrate": {"class(es)": ["Al"], "common name": "aluminum hydroxide", "id": 326},
  "alpha-alumina": {"class(es)": ["Al"], "common name": "alpha-alumina", "id": 327},
  "tetrabutyl titanate": {"class(es)": ["Ti"], "common name": "tetrabutyl titanate", "id": 328},
  "copper(II) sulfate pentahydrate": {"class(es)": ["Cu"], "common name": "copper(II) sulfate pentahydrate", "id": 329},
  "strontium nitrate": {"class(es)": ["Sr"], "common name": "strontium nitrate", "id": 330},
  "rice husk ash": {"class(es)": ["Si"], "common name": "rice husk ash", "id": 331},
  "fly ash": {"class(es)": ["Si", "Al"], "common name": "fly ash", "id": 332},
  "Sodium aluminate": {"class(es)": ["Al", "Na"], "common name": "sodium aluminate", "id": 333},
  "n-propyl alcohol": {"class(es)": ["None"], "common name": "n-propanol", "id": 334},
  "sililic acid": {"class(es)": ["Si"], "common name": "silicic acid", "id": 335},
  "disperal sol p2": {"class(es)": ["Al"], "common name": "dispersible boehmite alumina", "id": 336},
  "titanium tetrabutoxide": {"class(es)": ["Ti"], "common name": "titanium tetrabutoxide", "id": 337},
  "aluminum sulfate octadecahydrate": {"class(es)": ["Al"], "common name": "aluminum sulfate octadecahydrate", "id": 338},
  "Al isopropylate": {"class(es)": ["Al"], "common name": "aluminum isopropoxide", "id": 339},
  "fumed SiO2": {"class(es)": ["Si"], "common name": "fumed silica", "id": 340},
  "fumed silica": {"class(es)": ["Si"], "common name": "fumed silica", "id": 341},
  "TBOTi": {"class(es)": ["Ti"], "common name": "tetrabutyl orthotitanate", "id": 342},
  "Co(acetate)2": {"class(es)": ["Co"], "common name": "cobalt(II) acetate", "id": 343},
  "MFI": {"class(es)": ["Si", "Al"], "common name": "zeolite MFI", "id": 344},
  "FeCl3*6H2O": {"class(es)": ["Fe"], "common name": "ferric chloride hexahydrate", "id": 345},
  "hexanol": {"class(es)": ["None"], "common name": "hexanol", "id": 346},
  "Al(i-C3H7O)3": {"class(es)": ["Al"], "common name": "aluminum isopropoxide", "id": 347},
  "sodium meta silicate": {"class(es)": ["Si", "Na"], "common name": "sodium metasilicate", "id": 348},
  "zirconium(IV) oxide chloride": {"class(es)": ["Zr"], "common name": "zirconium oxychloride", "id": 349},
  "Al[OCH(CH3)2]3": {"class(es)": ["Al"], "common name": "aluminum isobutoxide", "id": 350},
  "H3AsO4": {"class(es)": ["As"], "common name": "arsenic acid", "id": 351},
  "zinc oxide": {"class(es)": ["Zn"], "common name": "zinc oxide", "id": 352},
  "ferric citrate": {"class(es)": ["Fe"], "common name": "ferric citrate", "id": 353},
  "zeolite Beta": {"class(es)": ["Si", "Al"], "common name": "zeolite Beta", "id": 354},
  "ultrasil": {"class(es)": ["Si"], "common name": "precipitated silica", "id": 355},
  "gadolinium nitrate": {"class(es)": ["Gd"], "common name": "gadolinium nitrate", "id": 356},
  "titanium(diisopropoxide)bis(2,4-pentanedionate)": {"class(es)": ["Ti"], "common name": "titanium isopropoxide acetylacetonate", "id": 357},
  "CsNO3": {"class(es)": ["Cs"], "common name": "cesium nitrate", "id": 358},
  "Banco N silicate": {"class(es)": ["Si", "Na"], "common name": "sodium silicate", "id": 359},
  "Levasil VP 4038": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 360},
  "B(OC2H5)3": {"class(es)": ["B"], "common name": "triethyl borate", "id": 361},
  "ZSM-12": {"class(es)": ["Si", "Al"], "common name": "zeolite ZSM-12", "id": 362},
  "NH4": {"class(es)": ["None"], "common name": "ammonium", "id": 363},
  "titanium glycolate": {"class(es)": ["Ti"], "common name": "titanium glycolate", "id": 364},
  "B2O3": {"class(es)": ["B"], "common name": "boron trioxide", "id": 365},
  "GeO2": {"class(es)": ["Ge"], "common name": "germanium dioxide", "id": 366},
  "diethoxydimethylsilane": {"class(es)": ["Si"], "common name": "diethoxydimethylsilane", "id": 367},
  "CrCl3": {"class(es)": ["Cr"], "common name": "chromium(III) chloride", "id": 368},
  "1-butanol": {"class(es)": ["None"], "common name": "1-butanol", "id": 369},
  "hydrated Al2O3": {"class(es)": ["Al"], "common name": "hydrated alumina", "id": 370},
  "aluminum foil": {"class(es)": ["Al"], "common name": "aluminum foil", "id": 371},
  "NiCl2*6H2O": {"class(es)": ["Ni"], "common name": "nickel(II) chloride hexahydrate", "id": 372},
  "sugarcane bagasse ash": {"class(es)": ["Si"], "common name": "sugarcane bagasse ash", "id": 373},
  "Al(OCH2CH3)3": {"class(es)": ["Al"], "common name": "aluminum ethoxide", "id": 374},
  "Aerosil-200": {"class(es)": ["Si"], "common name": "fumed silica", "id": 375},
  "RUB-18": {"class(es)": ["Si"], "common name": "zeolite RUB-18", "id": 376},
  "ammonia": {"class(es)": ["None"], "common name": "ammonia", "id": 377},
  "Cr(NO3)3": {"class(es)": ["Cr"], "common name": "chromium(III) nitrate", "id": 378},
  "copper acetate": {"class(es)": ["Cu"], "common name": "copper(II) acetate", "id": 379},
  "Silica": {"class(es)": ["Si"], "common name": "silica", "id": 380},
  "vanadyl sulphate": {"class(es)": ["V"], "common name": "vanadyl sulfate", "id": 381},
  "gallium nitrate hydrate": {"class(es)": ["Ga"], "common name": "gallium nitrate hydrate", "id": 382},
  "Ludox-As40": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 383},
  "Silicic acid": {"class(es)": ["Si"], "common name": "silicic acid", "id": 384},
  "nitric acid": {"class(es)": ["None"], "common name": "nitric acid", "id": 385},
  "Zn(NO3)2": {"class(es)": ["Zn"], "common name": "zinc nitrate", "id": 386},
  "lithium hydroxide monohydrate": {"class(es)": ["Li", "OH"], "common name": "lithium hydroxide monohydrate", "id": 387},
  "ludox": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 388},
  "nickel chloride": {"class(es)": ["Ni"], "common name": "nickel(II) chloride", "id": 389},
  "LiCl": {"class(es)": ["Li"], "common name": "lithium chloride", "id": 390},
  "Ludox AS-40": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 391},
  "silicon dioxide": {"class(es)": ["Si"], "common name": "silicon dioxide", "id": 392},
  "germanium(IV) oxide": {"class(es)": ["Ge"], "common name": "germanium dioxide", "id": 393},
  "silica extrudates": {"class(es)": ["Si"], "common name": "silica extrudates", "id": 394},
  "Ga(NO3)3": {"class(es)": ["Ga"], "common name": "gallium nitrate", "id": 395},
  "yttrium nitrate": {"class(es)": ["Y"], "common name": "yttrium nitrate", "id": 396},
  "silica amino": {"class(es)": ["Si"], "common name": "amino-modified silica", "id": 397},
  "pural SB": {"class(es)": ["Al"], "common name": "high purity alumina", "id": 398},
  "magnesium acetate": {"class(es)": ["Mg"], "common name": "magnesium acetate", "id": 399},
  "diatomite B": {"class(es)": ["Si"], "common name": "diatomaceous earth", "id": 400},
  "alumina": {"class(es)": ["Al"], "common name": "alumina", "id": 401},
  "Ludox HS-40": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 402},
  "oxalic acid": {"class(es)": ["None"], "common name": "oxalic acid", "id": 403},
  "silica": {"class(es)": ["Si"], "common name": "silica", "id": 404},
  "Na2Si2O3": {"class(es)": ["Si", "Na"], "common name": "sodium metasilicate", "id": 405},
  "CBV780": {"class(es)": ["Si", "Al"], "common name": "zeolite CBV780", "id": 406},
  "Aerosil 130": {"class(es)": ["Si"], "common name": "fumed silica", "id": 407},
  "titanium tetran-butoxide": {"class(es)": ["Ti"], "common name": "titanium tetrabutoxide", "id": 408},
  "Ceca sol": {"class(es)": ["Si"], "common name": "silica sol", "id": 409},
  "cobalt hydroxide": {"class(es)": ["Co"], "common name": "cobalt(II) hydroxide", "id": 410},
  "Rubidium hydroxide": {"class(es)": ["Rb", "OH"], "common name": "rubidium hydroxide", "id": 411},
  "Zn(NO3)2*9H20": {"class(es)": ["Zn"], "common name": "zinc nitrate nonahydrate", "id": 412},
  "NaAlO2": {"class(es)": ["Al", "Na"], "common name": "sodium aluminate", "id": 413},
  "caustic soda": {"class(es)": ["Na", "OH"], "common name": "sodium hydroxide", "id": 414},
  "glass": {"class(es)": ["Si"], "common name": "silica glass", "id": 415},
  "metallic aluminum": {"class(es)": ["Al"], "common name": "aluminum metal", "id": 416},
  "NH4Y zeolite": {"class(es)": ["Si", "Al"], "common name": "ammonium Y zeolite", "id": 417},
  "Al2(SO4)3*18H2O": {"class(es)": ["Al"], "common name": "aluminum sulfate octadecahydrate", "id": 418},
  "tripropylamine": {"class(es)": ["None"], "common name": "tripropylamine", "id": 419},
  "diatomite A": {"class(es)": ["Si", "Al"], "common name": "diatomaceous earth", "id": 420},
  "aluminum hydroxide": {"class(es)": ["Al"], "common name": "aluminum hydroxide", "id": 421},
  "Snowtex 40": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 422},
  "manganese carbonate": {"class(es)": ["Mn"], "common name": "manganese carbonate", "id": 423},
  "MgCl2*6H2O": {"class(es)": ["Mg"], "common name": "magnesium chloride hexahydrate", "id": 424},
  "Al powder": {"class(es)": ["Al"], "common name": "aluminum powder", "id": 425},
  "Ge(C2H5O)4": {"class(es)": ["Ge"], "common name": "germanium ethoxide", "id": 426},
  "Gibbsite": {"class(es)": ["Al"], "common name": "gibbsite", "id": 427},
  "faujasite": {"class(es)": ["Si", "Al"], "common name": "zeolite faujasite", "id": 428},
  "cupric acetrate monohydrate": {"class(es)": ["Cu"], "common name": "copper(II) acetate monohydrate", "id": 429},
  "germanium oxide": {"class(es)": ["Ge"], "common name": "germanium dioxide", "id": 430},
  "butanol": {"class(es)": ["None"], "common name": "butanol", "id": 431},
  "ethyl silicate 40": {"class(es)": ["Si"], "common name": "ethyl silicate", "id": 432},
  "iron(II) acetate": {"class(es)": ["Fe"], "common name": "iron(II) acetate", "id": 433},
  "e-Ga2O3": {"class(es)": ["Ga"], "common name": "epsilon gallium oxide", "id": 434},
  "manganese chloride tetrahydrate": {"class(es)": ["Mn"], "common name": "manganese(II) chloride tetrahydrate", "id": 435},
  "TEOS": {"class(es)": ["Si"], "common name": "tetraethyl orthosilicate", "id": 436},
  "VCl3": {"class(es)": ["V"], "common name": "vanadium(III) chloride", "id": 437},
  "solid aluminum": {"class(es)": ["Al"], "common name": "aluminum metal", "id": 438},
  "v2O5": {"class(es)": ["V"], "common name": "vanadium(V) oxide", "id": 439},
  "NH4-FAU": {"class(es)": ["Si", "Al"], "common name": "ammonium faujasite", "id": 440},
  "aluminate sulphate": {"class(es)": ["Al"], "common name": "aluminum sulfate", "id": 441},
  "Zn(NO3)2*6H2O": {"class(es)": ["Zn"], "common name": "zinc nitrate hexahydrate", "id": 442},
  "NH4F": {"class(es)": ["F"], "common name": "ammonium fluoride", "id": 443},
  "triethylene glycol": {"class(es)": ["None"], "common name": "triethylene glycol", "id": 444},
  "SnCl4": {"class(es)": ["Sn"], "common name": "tin(IV) chloride", "id": 445},
  "Pural SB": {"class(es)": ["Al"], "common name": "high purity alumina", "id": 446},
  "organoalkoxysilanes": {"class(es)": ["Si"], "common name": "organoalkoxysilanes", "id": 447},
  "sodium borate decahydrate": {"class(es)": ["B", "Na"], "common name": "sodium tetraborate decahydrate", "id": 448},
  "iron(II) sulfate": {"class(es)": ["Fe"], "common name": "iron(II) sulfate", "id": 449},
  "aluminum isopropoxide": {"class(es)": ["Al"], "common name": "aluminum isopropoxide", "id": 450},
  "silica colloidal": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 451},
  "NaY": {"class(es)": ["Si", "Al", "Na"], "common name": "sodium Y zeolite", "id": 452},
  "polyethlene glycol": {"class(es)": ["None"], "common name": "polyethylene glycol", "id": 453},
  "Be(OH)2": {"class(es)": ["Be"], "common name": "beryllium hydroxide", "id": 454},
  "vanadyl acetate": {"class(es)": ["V"], "common name": "vanadyl acetate", "id": 455},
  "titanium tetra-n-butoxide": {"class(es)": ["Ti"], "common name": "titanium tetrabutoxide", "id": 456},
  "zinc acetate": {"class(es)": ["Zn"], "common name": "zinc acetate", "id": 457},
  "Zn(CH3COO)2 * 2H2O": {"class(es)": ["Zn"], "common name": "zinc acetate dihydrate", "id": 458},
  "Al(NO3)": {"class(es)": ["Al"], "common name": "aluminum nitrate", "id": 459},
  "aluminum tri sec-butoxide": {"class(es)": ["Al"], "common name": "aluminum sec-butoxide", "id": 460},
  "iron nitrate": {"class(es)": ["Fe"], "common name": "iron(III) nitrate", "id": 461},
  "zirconium propoxide": {"class(es)": ["Zr"], "common name": "zirconium propoxide", "id": 462},
  "aluminum": {"class(es)": ["Al"], "common name": "aluminum", "id": 463},
  "phosphorus pentoxide": {"class(es)": ["P"], "common name": "phosphorus pentoxide", "id": 464},
  "TPOT": {"class(es)": ["Ti"], "common name": "tetrapropyl orthotitanate", "id": 465},
  "CBV712": {"class(es)": ["Si", "Al"], "common name": "zeolite CBV712", "id": 466},
  "Al foil": {"class(es)": ["Al"], "common name": "aluminum foil", "id": 467},
  "QUSO": {"class(es)": ["Si"], "common name": "silica gel", "id": 468},
  "gallium oxide(III) oxide": {"class(es)": ["Ga"], "common name": "gallium(III) oxide", "id": 469},
  "hydrobromic acid": {"class(es)": ["None"], "common name": "hydrobromic acid", "id": 470},
  "Na2SiO3*5H2O": {"class(es)": ["Si", "Na"], "common name": "sodium silicate pentahydrate", "id": 471},
  "NaSiO2": {"class(es)": ["Si", "Na"], "common name": "sodium metasilicate", "id": 472},
  "titanium(IV) sulfate": {"class(es)": ["Ti"], "common name": "titanium(IV) sulfate", "id": 473},
  "Ultrasil VN3": {"class(es)": ["Si"], "common name": "precipitated silica", "id": 474},
  "Fe(II) acetate": {"class(es)": ["Fe"], "common name": "iron(II) acetate", "id": 475},
  "vanadyl sulfate hydrate": {"class(es)": ["V"], "common name": "vanadyl sulfate hydrate", "id": 476},
  "colloidal Ludox": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 477},
  "Zeolite MAP": {"class(es)": ["None"], "common name": "zeolite MAP", "id": 478},
  "NaF": {"class(es)": ["Na", "F"], "common name": "sodium fluoride", "id": 479},
  "amorphous SiO2": {"class(es)": ["Si"], "common name": "amorphous silica", "id": 480},
  "Zeolite NaA": {"class(es)": ["Si", "Al"], "common name": "zeolite NaA", "id": 481},
  "Ludox TM-50": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 482},
  "Tosoh 390 HUA": {"class(es)": ["Si"], "common name": "zeolite Tosoh 390 HUA", "id": 483},
  "Al[O(s-Bu)]3": {"class(es)": ["Al"], "common name": "aluminum sec-butoxide", "id": 484},
  "sodium aluinate": {"class(es)": ["Al", "Na"], "common name": "sodium aluminate", "id": 485},
  "aluminium isopropoxide": {"class(es)": ["Al"], "common name": "aluminum isopropoxide", "id": 486},
  "cobalt sulfate": {"class(es)": ["Co"], "common name": "cobalt(II) sulfate", "id": 487},
  "H3PO3": {"class(es)": ["P"], "common name": "phosphorous acid", "id": 488},
  "CBV720": {"class(es)": ["Si", "Al"], "common name": "zeolite CBV720", "id": 489},
  "aluminum wire": {"class(es)": ["Al"], "common name": "aluminum wire", "id": 490},
  "hydrated aluminum": {"class(es)": ["Al"], "common name": "hydrated alumina", "id": 491},
  "APTES": {"class(es)": ["Si"], "common name": "(3-Aminopropyl)triethoxysilane", "id": 492},
  "iron(III) nitrate enneahyrate": {"class(es)": ["Fe"], "common name": "iron(III) nitrate nonahydrate", "id": 493},
  "Reheis": {"class(es)": ["Al"], "common name": "not specified", "id": 494},
  "TOSOH Y": {"class(es)": ["Si", "Al"], "common name": "zeolite TOSOH Y", "id": 495},
  "NH4-faujasite": {"class(es)": ["Si", "Al"], "common name": "ammonium faujasite", "id": 496},
  "cobalt acetate tetrahydrate": {"class(es)": ["Co"], "common name": "cobalt(II) acetate tetrahydrate", "id": 497},
  "ethyleneglycol": {"class(es)": ["None"], "common name": "ethylene glycol", "id": 498},
  "aluminum tri-sec-butoxide": {"class(es)": ["Al"], "common name": "aluminum sec-butoxide", "id": 499},
  "AlCl3": {"class(es)": ["Al"], "common name": "aluminum chloride", "id": 500},
  "cerium nitrate": {"class(es)": ["Ce"], "common name": "cerium(III) nitrate", "id": 501},
  "water glass": {"class(es)": ["Si", "Na"], "common name": "sodium silicate", "id": 502},
  "SnCl2": {"class(es)": ["Sn"], "common name": "tin(II) chloride", "id": 503},
  "sodium carbonate": {"class(es)": ["Na"], "common name": "sodium carbonate", "id": 504},
  "co(II) acetate": {"class(es)": ["Co"], "common name": "cobalt(II) acetate", "id": 505},
  "NaAl": {"class(es)": ["Al", "Na"], "common name": "sodium aluminate", "id": 506},
  "tetraethylene glycol": {"class(es)": ["None"], "common name": "tetraethylene glycol", "id": 507},
  "titanium butoxide": {"class(es)": ["Ti"], "common name": "titanium butoxide", "id": 508},
  "As2O3": {"class(es)": ["As"], "common name": "arsenic trioxide", "id": 509},
  "FeC2O4": {"class(es)": ["Fe"], "common name": "iron(II) oxalate", "id": 510},
  "aluminum iso-butoxide": {"class(es)": ["Al"], "common name": "aluminum isobutoxide", "id": 511},
  "aluminium hydroxide": {"class(es)": ["Al"], "common name": "aluminum hydroxide", "id": 512},
  "Ludox LS 30": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 513},
  "na-aluminate": {"class(es)": ["Al", "Na"], "common name": "sodium aluminate", "id": 514},
  "chromium(III) nitride": {"class(es)": ["Cr"], "common name": "chromium nitride", "id": 515},
  "Ludox TM-40": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 516},
  "cobalt carbonate": {"class(es)": ["Co"], "common name": "cobalt(II) carbonate", "id": 517},
  "silicon sol": {"class(es)": ["Si"], "common name": "silicon sol", "id": 518},
  "sodium metaborate tetrahydrate": {"class(es)": ["Na", "B"], "common name": "sodium metaborate tetrahydrate", "id": 519},
  "colloidal silica": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 520},
  "magnesium nitrate hexahydrate": {"class(es)": ["Mg"], "common name": "magnesium nitrate hexahydrate", "id": 521},
  "silica aerosil": {"class(es)": ["Si"], "common name": "fumed silica", "id": 522},
  "sodium metagermanate": {"class(es)": ["Ge", "Na"], "common name": "sodium metagermanate", "id": 523},
  "carbonic acid": {"class(es)": ["None"], "common name": "carbonic acid", "id": 524},
  "tetraethoxysilane": {"class(es)": ["Si"], "common name": "tetraethyl orthosilicate", "id": 525},
  "catapal B": {"class(es)": ["Al"], "common name": "alpha-alumina", "id": 526},
  "metallic aluminum": {"class(es)": ["Al"], "common name": "aluminum metal", "id": 527},
  "Ludox JN-30": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 528},
  "H-Y zeolites": {"class(es)": ["Si", "Al"], "common name": "H-Y zeolite", "id": 529},
  "ethanol": {"class(es)": ["None"], "common name": "ethanol", "id": 530},
  "mekakaolinite": {"class(es)": ["Si", "Al"], "common name": "metakaolin", "id": 531},
  "H-Kanemite": {"class(es)": ["Si", "Na"], "common name": "kanemite", "id": 532},
  "Aluminum hydroxide": {"class(es)": ["Al"], "common name": "aluminum hydroxide", "id": 533},
  "Cab-O-Sil M5": {"class(es)": ["Si"], "common name": "fumed silica", "id": 534},
  "Co-FAU": {"class(es)": ["Si", "Al"], "common name": "cobalt-exchanged zeolite FAU", "id": 535},
  "NaOH": {"class(es)": ["Na", "OH"], "common name": "sodium hydroxide", "id": 536},
  "AlF3*3H2O": {"class(es)": ["Al", "F"], "common name": "aluminum fluoride trihydrate", "id": 537},
  "potassium silicate": {"class(es)": ["Si", "K"], "common name": "potassium silicate", "id": 538},
  "Reheis F-2000": {"class(es)": ["Al"], "common name": "aluminum hydroxide", "id": 539},
  "ST01": {"class(es)": ["Si"], "common name": "not specified", "id": 540},
  "lanthanum nitrate": {"class(es)": ["La"], "common name": "lanthanum nitrate", "id": 541},
  "arsenic acid": {"class(es)": ["As"], "common name": "arsenic acid", "id": 542},
  "Ga2(SO4)3*18H2O": {"class(es)": ["Ga"], "common name": "gallium sulfate octadecahydrate", "id": 543},
  "MnF3": {"class(es)": ["Mn"], "common name": "manganese(III) fluoride", "id": 544},
  "alumina hydroxide": {"class(es)": ["Al"], "common name": "aluminum hydroxide", "id": 545},
  "fumed silica": {"class(es)": ["Si"], "common name": "fumed silica", "id": 546},
  "V2O3": {"class(es)": ["V"], "common name": "vanadium(III) oxide", "id": 547},
  "Cobalt acetate": {"class(es)": ["Co"], "common name": "cobalt(II) acetate", "id": 548},
  "basic silica sol": {"class(es)": ["Si"], "common name": "basic colloidal silica", "id": 549},
  "Mg(CH3COO)2*4H2O": {"class(es)": ["Mg"], "common name": "magnesium acetate tetrahydrate", "id": 550},
  "TMOS": {"class(es)": ["Si"], "common name": "tetramethyl orthosilicate", "id": 551},
  "M-5": {"class(es)": ["Si", "Al"], "common name": "zeolite M-5", "id": 552},
  "TEG": {"class(es)": ["None"], "common name": "triethylene glycol", "id": 553},
  "zirconium(IV) isopropoxide": {"class(es)": ["Zr"], "common name": "zirconium isopropoxide", "id": 554},
  "nordstrandite": {"class(es)": ["Al"], "common name": "nordstrandite", "id": 555},
  "Al(OH)3": {"class(es)": ["Al"], "common name": "aluminum hydroxide", "id": 556},
  "chromium(III) chloride hexahydrate": {"class(es)": ["Cr"], "common name": "chromium(III) chloride hexahydrate", "id": 557},
  "iso-Al(OC3H7)3": {"class(es)": ["Al"], "common name": "aluminum isopropoxide", "id": 558},
  "Ludox AS": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 559},
  "silicic acid": {"class(es)": ["Si"], "common name": "silicic acid", "id": 560},
  "alumina isopropoxide": {"class(es)": ["Al"], "common name": "aluminum isopropoxide", "id": 561},
  "zeolite Y": {"class(es)": ["None"], "common name": "zeolite Y", "id": 562},
  "Al2(SO4)3": {"class(es)": ["Al"], "common name": "aluminum sulfate", "id": 563},
  "aerosil": {"class(es)": ["Si"], "common name": "fumed silica", "id": 564},
  "Snowtex-40": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 565},
  "NaOH ": {"class(es)": ["Na", "OH"], "common name": "sodium hydroxide", "id": 566},
  "FKET": {"class(es)": ["None"], "common name": "not specified", "id": 567},
  "bamboo leaves ash": {"class(es)": ["Si"], "common name": "bamboo leaves ash", "id": 568},
  "Mg(OH)2": {"class(es)": ["Mg"], "common name": "magnesium hydroxide", "id": 569},
  "white carbon black": {"class(es)": ["Si"], "common name": "silica", "id": 570},
  "Al2(NO3)3": {"class(es)": ["Al"], "common name": "aluminum nitrate", "id": 571},
  "hydrophilic fumed silica": {"class(es)": ["Si"], "common name": "hydrophilic fumed silica", "id": 572},
  "SnCl4*5H2O": {"class(es)": ["Sn"], "common name": "tin(IV) chloride pentahydrate", "id": 573},
  "silica gel": {"class(es)": ["Si"], "common name": "silica gel", "id": 574},
  "aerosil silica": {"class(es)": ["Si"], "common name": "fumed silica", "id": 575},
  "Wairakei silica": {"class(es)": ["Si"], "common name": "Wairakei silica", "id": 576},
  "Al[O(s-BU)]3": {"class(es)": ["Al"], "common name": "aluminum sec-butoxide", "id": 577},
  "Brij-35": {"class(es)": ["None"], "common name": "polyethylene glycol dodecyl ether", "id": 578},
  "aluminum sulfate hydrate": {"class(es)": ["Al"], "common name": "aluminum sulfate hydrate", "id": 579},
  "Co(Oac)2": {"class(es)": ["Co"], "common name": "cobalt(II) acetate", "id": 580},
  "Silicon tetrachloride": {"class(es)": ["None"], "common name": "silicon tetrachloride", "id": 581},
  "Cataloid SI30": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 582},
  "Al(OC3H7)3": {"class(es)": ["Al"], "common name": "aluminum isopropoxide", "id": 583},
  "vanadyl acetylacetonate": {"class(es)": ["V"], "common name": "vanadyl acetylacetonate", "id": 584},
  "precipitated silica": {"class(es)": ["Si"], "common name": "precipitated silica", "id": 585},
  "microsil silica": {"class(es)": ["Si"], "common name": "not specified", "id": 586},
  "CHA": {"class(es)": ["Si", "Al"], "common name": "not specified", "id": 587},
  "tetraethyl orthotitanate": {"class(es)": ["Ti"], "common name": "tetraethyl orthotitanate", "id": 588},
  "sodium metaaluminate": {"class(es)": ["Al", "Na"], "common name": "sodium metaaluminate", "id": 589},
  "phosphorous acid": {"class(es)": ["P"], "common name": "phosphorous acid", "id": 590},
  "hafnium(IV) chloride": {"class(es)": ["Hf"], "common name": "hafnium(IV) chloride", "id": 591},
  "Cs2CO3": {"class(es)": ["Cs"], "common name": "cesium carbonate", "id": 592},
  "TNBT": {"class(es)": ["Ti"], "common name": "not specified", "id": 593},
  "aluminium hydroxide hydrate": {"class(es)": ["Al"], "common name": "aluminum hydroxide", "id": 594},
  "Ti(OtBu)4": {"class(es)": ["Ti"], "common name": "titanium tetrabutoxide", "id": 595},
  "Ultrasil 3VN": {"class(es)": ["Si"], "common name": "not specified", "id": 596},
  "colloid silica": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 597},
  "precipiated silica": {"class(es)": ["Si"], "common name": "precipitated silica", "id": 598},
  "NaCl": {"class(es)": ["Na"], "common name": "sodium chloride", "id": 599},
  "alumina trihydrate": {"class(es)": ["Al"], "common name": "aluminum hydroxide", "id": 600},
  "triisopropylaluminum": {"class(es)": ["Al"], "common name": "triisopropylaluminum", "id": 601},
  "HSZ-373HUA": {"class(es)": ["Si", "Al"], "common name": "zeolite HSZ-373HUA", "id": 602},
  "cobalt chloride": {"class(es)": ["Co"], "common name": "cobalt(II) chloride", "id": 603},
  "sodium metasilicate": {"class(es)": ["Si", "Na"], "common name": "sodium metasilicate", "id": 604},
  "manganese acetate tetrahydrate": {"class(es)": ["Mn"], "common name": "manganese(II) acetate tetrahydrate", "id": 605},
  "aerosils": {"class(es)": ["Si"], "common name": "fumed silica", "id": 606},
  "metal aluminum": {"class(es)": ["Al"], "common name": "aluminum metal", "id": 607},
  "sodium tetraborate": {"class(es)": ["B", "Na"], "common name": "sodium tetraborate (borax)", "id": 608},
  "Nipsil": {"class(es)": ["Si"], "common name": "not specified", "id": 609},
  "Ludox AS30": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 610},
  "Fe2O3": {"class(es)": ["Fe"], "common name": "iron(III) oxide", "id": 611},
  "tetrabutyltitanate": {"class(es)": ["Ti"], "common name": "tetrabutyl titanate", "id": 612},
  "Ludox LS": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 613},
  "Na4P2O7": {"class(es)": ["Na", "P"], "common name": "sodium pyrophosphate", "id": 614},
  "gallium": {"class(es)": ["Ga"], "common name": "gallium metal", "id": 615},
  "*BEA": {"class(es)": ["Si", "Al"], "common name": "zeolite *BEA", "id": 616},
  "SnO2": {"class(es)": ["Sn"], "common name": "tin(IV) oxide", "id": 617},
  "alumina sol": {"class(es)": ["Al"], "common name": "alumina sol", "id": 618},
  "Fe(NO3)3*9H2O": {"class(es)": ["Fe"], "common name": "iron(III) nitrate nonahydrate", "id": 619},
  "NaGaO2": {"class(es)": ["Na", "Ga"], "common name": "sodium gallate", "id": 620},
  "Cab-o-sil M5": {"class(es)": ["Si"], "common name": "fumed silica", "id": 621},
  "potassium nitrate": {"class(es)": ["K"], "common name": "potassium nitrate", "id": 622},
  "FAU zeolite": {"class(es)": ["Si", "Al"], "common name": "zeolite FAU", "id": 623},
  "HCl": {"class(es)": ["None"], "common name": "hydrochloric acid", "id": 624},
  "ammonium hydrogenphosphate": {"class(es)": ["P"], "common name": "ammonium phosphate", "id": 625},
  "titanium isoproxide": {"class(es)": ["Ti"], "common name": "titanium isopropoxide", "id": 626},
  "Tosil": {"class(es)": ["Si"], "common name": "not specified", "id": 627},
  "aluminum triisopropoxide": {"class(es)": ["Al"], "common name": "aluminum isopropoxide", "id": 628},
  "hydrated cerium chloride": {"class(es)": ["Ce"], "common name": "cerium(III) chloride hydrate", "id": 629},
  "CuAc2": {"class(es)": ["Cu"], "common name": "copper(II) acetate", "id": 630},
  "Pural SB-1": {"class(es)": ["Al"], "common name": "high purity alumina", "id": 631},
  "Ludox silica": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 632},
  "CBV760": {"class(es)": ["Si", "Al"], "common name": "zeolite CBV760", "id": 633},
  "titanium tetrachloride": {"class(es)": ["Ti"], "common name": "titanium tetrachloride", "id": 634},
  "chromium (III) nitrate nonahydrate": {"class(es)": ["Cr"], "common name": "chromium(III) nitrate nonahydrate", "id": 635},
  "cabosil M5": {"class(es)": ["Si"], "common name": "fumed silica", "id": 636},
  "Brij-56": {"class(es)": ["None"], "common name": "not specified", "id": 637},
  "Co acetate tetrahydrate": {"class(es)": ["Co"], "common name": "cobalt(II) acetate tetrahydrate", "id": 638},
  "sodium borate": {"class(es)": ["B", "Na"], "common name": "sodium borate", "id": 639},
  "GaOOH": {"class(es)": ["Ga"], "common name": "gallium oxyhydroxide", "id": 640},
  "CuO": {"class(es)": ["Cu"], "common name": "copper(II) oxide", "id": 641},
  "Zn(CH3COO)2": {"class(es)": ["Zn"], "common name": "zinc acetate", "id": 642},
  "silica-alumina microsphere": {"class(es)": ["Si", "Al"], "common name": "silica-alumina microspheres", "id": 643},
  "silica fume": {"class(es)": ["Si"], "common name": "silica fume", "id": 644},
  "titanium isopropoxide": {"class(es)": ["Ti"], "common name": "titanium isopropoxide", "id": 645},
  "rice straw": {"class(es)": ["None"], "common name": "rice straw ash", "id": 646},
  "Sylobloc 47": {"class(es)": ["Si"], "common name": "silica powder", "id": 647},
  "HSZ-390HUA": {"class(es)": ["Si", "Al"], "common name": "zeolite HSZ-390HUA", "id": 648},
  "N,N-dimethylformamide": {"class(es)": ["None"], "common name": "N,N-dimethylformamide", "id": 649},
  "NaBr": {"class(es)": ["Na"], "common name": "sodium bromide", "id": 650},
  "Zn(Oac)2*2H2O": {"class(es)": ["Zn"], "common name": "zinc acetate dihydrate", "id": 651},
  "titanium(IV) ethoxide": {"class(es)": ["Ti"], "common name": "titanium(IV) ethoxide", "id": 652},
  "CabOSil M5": {"class(es)": ["Si"], "common name": "fumed silica", "id": 653},
  "gibbsite": {"class(es)": ["Al"], "common name": "gibbsite", "id": 654},
  "iron(III) sulfate n-hydrate": {"class(es)": ["Fe"], "common name": "iron(III) sulfate hydrate", "id": 655},
  "ZnCl2": {"class(es)": ["Zn"], "common name": "zinc chloride", "id": 656},
  "t-butyl orthotitanate": {"class(es)": ["Ti"], "common name": "tetrabutyl orthotitanate", "id": 657},
  "titanium(IV) n-butoxide": {"class(es)": ["Ti"], "common name": "titanium(IV) butoxide", "id": 658},
  "catapal A alumina": {"class(es)": ["Al"], "common name": "alpha-alumina", "id": 659},
  "Mg3(PO4)2": {"class(es)": ["Mg"], "common name": "magnesium phosphate", "id": 660},
  "vandadium pentoxide": {"class(es)": ["V"], "common name": "vanadium(V) oxide", "id": 661},
  "Snowtex-N": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 662},
  "o-phosphoric acid": {"class(es)": ["P"], "common name": "orthophosphoric acid", "id": 663},
  "Cr acetate": {"class(es)": ["Cr"], "common name": "chromium(III) acetate", "id": 664},
  "kanemite": {"class(es)": ["Si", "Na"], "common name": "kanemite", "id": 665},
  "Al(OH3)*H2O": {"class(es)": ["Al"], "common name": "aluminum hydroxide hydrate", "id": 666},
  "colloidal silica sol": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 667},
  "CoCO3": {"class(es)": ["Co"], "common name": "cobalt(II) carbonate", "id": 668},
  "Ludox-AS-40": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 669},
  "manganese(II) acetate tetrahydrate": {"class(es)": ["Mn"], "common name": "manganese(II) acetate tetrahydrate", "id": 670},
  "silatrane": {"class(es)": ["Si"], "common name": "silatrane", "id": 671},
  "Mg(CH3COO)2": {"class(es)": ["Mg"], "common name": "magnesium acetate", "id": 672},
  "HSZ-350HUA": {"class(es)": ["Si", "Al"], "common name": "zeolite HSZ-350HUA", "id": 673},
  "Ludox LS-40": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 674},
  "cobalt(II) chloride": {"class(es)": ["Co"], "common name": "cobalt(II) chloride", "id": 675},
  "metakolin": {"class(es)": ["Si", "Al"], "common name": "metakaolin", "id": 676},
  "glycerine": {"class(es)": ["None"], "common name": "glycerol", "id": 677},
  "Phosphoric acid": {"class(es)": ["P"], "common name": "phosphoric acid", "id": 678},
  "o-H3PO4": {"class(es)": ["P"], "common name": "orthophosphoric acid", "id": 679},
  "USY CBV500": {"class(es)": ["Si", "Al"], "common name": "ultra-stable Y zeolite", "id": 680},
  "metakaolin": {"class(es)": ["Si", "Al"], "common name": "metakaolin", "id": 681},
  "Ludox W-30": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 682},
  "succinic acid": {"class(es)": ["None"], "common name": "succinic acid", "id": 683},
  "cerium nitrate hex hydrate": {"class(es)": ["Ce"], "common name": "cerium(III) nitrate hexahydrate", "id": 684},
  "titanium (di-isopropoxide)bis(acetylacetonate": {"class(es)": ["Ti"], "common name": "titanium diisopropoxide bis(acetylacetonate)", "id": 685},
  "aluminum tri-ispropoxide": {"class(es)": ["Al"], "common name": "aluminum isopropoxide", "id": 686},
  "TIP": {"class(es)": ["Ti"], "common name": "titanium isopropoxide", "id": 687},
  "aluminum metal": {"class(es)": ["Al"], "common name": "aluminum", "id": 688},
  "perchloric acid": {"class(es)": ["None"], "common name": "perchloric acid", "id": 689},
  "H3BO3": {"class(es)": ["B"], "common name": "boric acid", "id": 690},
  "aluminum fluoride trihydrate": {"class(es)": ["Al", "F"], "common name": "aluminum fluoride trihydrate", "id": 691},
  "kaolinite": {"class(es)": ["Si", "Al"], "common name": "kaolinite", "id": 692},
  "330HUA": {"class(es)": ["Si", "Al"], "common name": "not specified", "id": 693},
  "aerosol": {"class(es)": ["Si"], "common name": "not specified", "id": 694},
  "al powder": {"class(es)": ["Al"], "common name": "aluminum powder", "id": 695},
  "aluminum hydrate": {"class(es)": ["Al"], "common name": "aluminum hydroxide", "id": 696},
  "hydrated silica": {"class(es)": ["Si"], "common name": "hydrated silica", "id": 697},
  "Zeolite Y CBV-720": {"class(es)": ["Si", "Al"], "common name": "zeolite Y CBV-720", "id": 698},
  "Ludox PW-50": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 699},
  "pseudo-boehmite": {"class(es)": ["Al"], "common name": "pseudo-boehmite", "id": 700},
  "sulphuric acid": {"class(es)": ["None"], "common name": "sulfuric acid", "id": 701},
  "silica sol": {"class(es)": ["Si"], "common name": "silica sol", "id": 702},
  "FAU": {"class(es)": ["Si", "Al"], "common name": "zeolite FAU", "id": 703},
  "potassium aluminate": {"class(es)": ["Al", "K"], "common name": "potassium aluminate", "id": 704},
  "ZSM-5": {"class(es)": ["Si", "Al"], "common name": "zeolite ZSM-5", "id": 705},
  "iron(III) chloride": {"class(es)": ["Fe"], "common name": "iron(III) chloride", "id": 706},
  "Co(Oac)2*4H2O": {"class(es)": ["Co"], "common name": "cobalt(II) acetate tetrahydrate", "id": 707},
  "TBOT": {"class(es)": ["Ti"], "common name": "tetrabutyl orthotitanate", "id": 708},
  "MnCl2*4H2O": {"class(es)": ["Mn"], "common name": "manganese(II) chloride tetrahydrate", "id": 709},
  "zinc acetate diydrate": {"class(es)": ["Zn"], "common name": "zinc acetate dihydrate", "id": 710},
  "alumoaerosil": {"class(es)": ["Si", "Al"], "common name": "alumina-silica aerogel", "id": 711},
  "NaX": {"class(es)": ["Na", "Si", "Al"], "common name": "zeolite NaX", "id": 712},
  "TMAsilicate": {"class(es)": ["Si"], "common name": "trimethylsilyl silicate", "id": 713},
  "isopropanol": {"class(es)": ["None"], "common name": "isopropanol", "id": 714},
  "silica aerogel": {"class(es)": ["Si"], "common name": "silica aerogel", "id": 715},
  "TEOT": {"class(es)": ["Si"], "common name": "tetraethyl orthotitanate", "id": 716},
  "DuPont HS-40": {"class(es)": ["Si"], "common name": "Ludox", "id": 717},
  "SrCl2": {"class(es)": ["Sr"], "common name": "strontium chloride", "id": 718},
  "n-hexanol": {"class(es)": ["None"], "common name": "n-hexanol", "id": 719},
  "Aerosil 90": {"class(es)": ["Si"], "common name": "fumed silica", "id": 720},
  "silica spheres": {"class(es)": ["Si"], "common name": "silica spheres", "id": 721},
  "1-hexanol": {"class(es)": ["None"], "common name": "1-hexanol", "id": 722},
  "Ethanol": {"class(es)": ["None"], "common name": "ethanol", "id": 723},
  "29SiO2": {"class(es)": ["Si"], "common name": "silicon dioxide", "id": 724},
  "iron acetate": {"class(es)": ["None"], "common name": "iron(II) acetate", "id": 725},
  "Cab-o-Sil M5": {"class(es)": ["Si"], "common name": "fumed silica", "id": 726},
  "aluminum-tri-sec-butoxide": {"class(es)": ["Al"], "common name": "aluminum sec-butoxide", "id": 727},
  "ZnC2O4": {"class(es)": ["Zn"], "common name": "zinc oxalate", "id": 728},
  "TEOTi": {"class(es)": ["Ti"], "common name": "titanium ethoxide", "id": 729},
  "aluminum tri-isopropoxide": {"class(es)": ["Al"], "common name": "aluminum isopropoxide", "id": 730},
  "Ludox HS40": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 731},
  "HSZ-390": {"class(es)": ["Si", "Al"], "common name": "zeolite HSZ-390", "id": 732},
  "boric acid": {"class(es)": ["B"], "common name": "boric acid", "id": 733},
  "chromium(III) acetate": {"class(es)": ["Cr"], "common name": "chromium(III) acetate", "id": 734},
  "aluminum flakes": {"class(es)": ["Al"], "common name": "aluminum flakes", "id": 735},
  "sodium hydroxide": {"class(es)": ["Na", "OH"], "common name": "sodium hydroxide", "id": 736},
  "La(NO3)3": {"class(es)": ["La"], "common name": "lanthanum nitrate", "id": 737},
  "Aluminum triisopropoxide": {"class(es)": ["Al"], "common name": "aluminum isopropoxide", "id": 738},
  "vanadysulphate trihydrate": {"class(es)": ["V"], "common name": "vanadyl sulfate trihydrate", "id": 739},
  "[Al]-BEA": {"class(es)": ["Si", "Al"], "common name": "aluminosilicate BEA", "id": 740},
  "cobalt(II) acetate": {"class(es)": ["Co"], "common name": "cobalt(II) acetate", "id": 741},
  "Vanadyl sulfate tri-hydrate": {"class(es)": ["V"], "common name": "vanadyl sulfate trihydrate", "id": 742},
  "NiCl2": {"class(es)": ["Ni"], "common name": "nickel(II) chloride", "id": 743},
  "ITQ-1": {"class(es)": ["Si"], "common name": "zeolite ITQ-1", "id": 744},
  "Cabosil M-5": {"class(es)": ["Si"], "common name": "fumed silica", "id": 745},
  "waterglass": {"class(es)": ["Si", "Na"], "common name": "sodium silicate", "id": 746},
  "zinc sulfate": {"class(es)": ["Zn"], "common name": "zinc sulfate", "id": 747},
  "colloidal silica snowtex-N": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 748},
  "zinc acetate dihydrate": {"class(es)": ["Zn"], "common name": "zinc acetate dihydrate", "id": 749},
  "MnCO3": {"class(es)": ["Mn"], "common name": "manganese(II) carbonate", "id": 750},
  "Ludox AM-30": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 751},
  "CoCO3*xH2O": {"class(es)": ["Co"], "common name": "cobalt(II) carbonate hydrate", "id": 752},
  "titanium (IV) isopropoxide": {"class(es)": ["Ti"], "common name": "titanium isopropoxide", "id": 753},
  "zinc(II) acetate dihydrate": {"class(es)": ["Zn"], "common name": "zinc acetate dihydrate", "id": 754},
  "elemental aluminum": {"class(es)": ["Al"], "common name": "aluminum", "id": 755},
  "TTIP": {"class(es)": ["Ti"], "common name": "titanium tetraisopropoxide", "id": 756},
  "CuCl2": {"class(es)": ["Cu"], "common name": "copper(II) chloride", "id": 757},
  "sodium aluminosilicate": {"class(es)": ["Si", "Al", "Na"], "common name": "sodium aluminosilicate", "id": 758},
  "propane-1,3-diol": {"class(es)": ["None"], "common name": "propane-1,3-diol", "id": 759},
  "biomass fly ash": {"class(es)": ["Si", "Al"], "common name": "biomass fly ash", "id": 760},
  "CsOH": {"class(es)": ["Cs", "OH"], "common name": "cesium hydroxide", "id": 761},
  "HSZ-370HUA": {"class(es)": ["Si", "Al"], "common name": "zeolite HSZ-370HUA", "id": 762},
  "nickel acetate": {"class(es)": ["Ni"], "common name": "nickel(II) acetate", "id": 763},
  "sodium sulfate": {"class(es)": ["Na"], "common name": "sodium sulfate", "id": 764},
  "ortho-phosphoric acid": {"class(es)": ["P"], "common name": "orthophosphoric acid", "id": 765},
  "Ludox AM": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 766},
  "KF": {"class(es)": ["K", "F"], "common name": "potassium fluoride", "id": 767},
  "Ti(Obu)4": {"class(es)": ["Ti"], "common name": "titanium tetrabutoxide", "id": 768},
  "Caesium hydroxide": {"class(es)": ["Cs", "OH"], "common name": "cesium hydroxide", "id": 769},
  "HSZ-331HSA": {"class(es)": ["Si", "Al"], "common name": "zeolite HSZ-331HSA", "id": 770},
  "Ludox HS": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 771},
  "NH4-Y zeolite ": {"class(es)": ["Si", "Al"], "common name": "ammonium Y zeolite", "id": 772},
  "Ludox SM-30": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 773},
  "Si(Oet)4": {"class(es)": ["Si"], "common name": "tetraethyl orthosilicate", "id": 774},
  "Hi-Sil 233-D": {"class(es)": ["Si"], "common name": "precipitated silica", "id": 775},
  "zirconium nitrate hexahydrate": {"class(es)": ["Zr"], "common name": "zirconium nitrate hexahydrate", "id": 776},
  "ZnO": {"class(es)": ["Zn"], "common name": "zinc oxide", "id": 777},
  "chromium nitrate": {"class(es)": ["Cr"], "common name": "chromium(III) nitrate", "id": 778},
  "Reheis F2000": {"class(es)": ["Al"], "common name": "aluminum hydroxide", "id": 779},
  "MCM-22": {"class(es)": ["Si"], "common name": "zeolite MCM-22", "id": 780},
  "Al(NO3)3*9H2O": {"class(es)": ["Al"], "common name": "aluminum nitrate nonahydrate", "id": 781},
  "sodium metaaluminate": {"class(es)": ["Al", "Na"], "common name": "sodium metaaluminate", "id": 782},
  "propyltriethoxysilane": {"class(es)": ["Si"], "common name": "propyltriethoxysilane", "id": 783},
  "boron oxide": {"class(es)": ["B"], "common name": "boron trioxide", "id": 784},
  "powdered aluminum": {"class(es)": ["Al"], "common name": "aluminum powder", "id": 785},
  "Aerosil 200": {"class(es)": ["Si"], "common name": "fumed silica", "id": 786},
  "zinc nitrate": {"class(es)": ["Zn"], "common name": "zinc nitrate", "id": 787},
  "copper sulfate": {"class(es)": ["Cu"], "common name": "copper(II) sulfate", "id": 788},
  "nickel acetate tetrahydrate": {"class(es)": ["Ni"], "common name": "nickel(II) acetate tetrahydrate", "id": 789},
  "Ludox As-30": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 790},
  "Q-brand sodium silicate": {"class(es)": ["Si", "Na"], "common name": "sodium silicate", "id": 791},
  "polyphosphoric acid": {"class(es)": ["P"], "common name": "polyphosphoric acid", "id": 792},
  "magnesium chloride": {"class(es)": ["Mg"], "common name": "magnesium chloride", "id": 793},
  "tantalum chloride": {"class(es)": ["Ta"], "common name": "tantalum chloride", "id": 794},
  "ferric ammonium citrate": {"class(es)": ["Fe"], "common name": "ferric ammonium citrate", "id": 795},
  "orthoboric acid": {"class(es)": ["B"], "common name": "boric acid", "id": 796},
  "Mg(NO3)3": {"class(es)": ["Mg"], "common name": "magnesium nitrate", "id": 797},
  "Ludox-30": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 798},
  "Al(Opri)3": {"class(es)": ["Al"], "common name": "aluminum isopropoxide", "id": 799},
  "iron(III) nitrate": {"class(es)": ["Fe"], "common name": "iron(III) nitrate", "id": 800},
  "ammonium ferric citrate": {"class(es)": ["Fe"], "common name": "ammonium ferric citrate", "id": 801},
  "toluene": {"class(es)": ["None"], "common name": "toluene", "id": 802},
  "LiOH": {"class(es)": ["Li", "OH"], "common name": "lithium hydroxide", "id": 803},
  "(CH3COO)2Zn": {"class(es)": ["Zn"], "common name": "zinc acetate", "id": 804},
  "titanium(IV) isopropoxide": {"class(es)": ["Ti"], "common name": "titanium isopropoxide", "id": 805},
  "Si(Oethyl)4": {"class(es)": ["Si"], "common name": "tetraethyl orthosilicate", "id": 806},
  "In2O3": {"class(es)": ["In"], "common name": "indium(III) oxide", "id": 807},
  "gallia": {"class(es)": ["Ga"], "common name": "gallium oxide", "id": 808},
  "Al2O3": {"class(es)": ["Al"], "common name": "alumina", "id": 809},
  "aluminum nitrate": {"class(es)": ["Al"], "common name": "aluminum nitrate", "id": 810},
  "B(OH)3": {"class(es)": ["B"], "common name": "boric acid", "id": 811},
  "titanium ethoxide": {"class(es)": ["Ti"], "common name": "titanium ethoxide", "id": 812},
  "PTEOS": {"class(es)": ["Si"], "common name": "phenyltriethoxysilane", "id": 813},
  "sodium carbonate decahydrate": {"class(es)": ["Na"], "common name": "sodium carbonate decahydrate", "id": 814},
  "OS-18": {"class(es)": ["None"], "common name": "not specified", "id": 815},
  "Germanium oxide": {"class(es)": ["Ge"], "common name": "germanium oxide", "id": 816},
  "cobalt nitrate": {"class(es)": ["Co"], "common name": "cobalt(II) nitrate", "id": 817},
  "Beta": {"class(es)": ["Si", "Al"], "common name": "zeolite Beta", "id": 818},
  "Ludox HS-30": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 819},
  "ethylene glycol": {"class(es)": ["None"], "common name": "ethylene glycol", "id": 820},
  "Mn(II) acetylacetonate": {"class(es)": ["Mn"], "common name": "manganese(II) acetylacetonate", "id": 821},
  "colloidal silicaTM-40": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 822},
  "ruthenium(III) chloride": {"class(es)": ["Ru"], "common name": "ruthenium(III) chloride", "id": 823},
  "Germanium dioxide": {"class(es)": ["Ge"], "common name": "germanium dioxide", "id": 824},
  "Na2B4O7": {"class(es)": ["B", "Na"], "common name": "sodium tetraborate (borax)", "id": 825},
  "silica solution": {"class(es)": ["Si"], "common name": "silica solution", "id": 826},
  "ZrOCl2*8H2O": {"class(es)": ["Zr"], "common name": "zirconium oxychloride octahydrate", "id": 827},
  "Versal 450": {"class(es)": ["Al"], "common name": "alumina", "id": 828},
  "Pseudoboehmite": {"class(es)": ["Al"], "common name": "pseudo-boehmite", "id": 829},
  "ferrouis sulfate heptahydrate": {"class(es)": ["Fe"], "common name": "ferrous sulfate heptahydrate", "id": 830},
  "Ludox HS 40": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 831},
  "biphenyl": {"class(es)": ["None"], "common name": "biphenyl", "id": 832},
  "glycol": {"class(es)": ["None"], "common name": "ethylene glycol", "id": 833},
  "polyethylene glycol": {"class(es)": ["None"], "common name": "polyethylene glycol", "id": 834},
  "N-brand sodium silicate": {"class(es)": ["Si", "Na"], "common name": "sodium silicate", "id": 835},
  "PrTES": {"class(es)": ["Si"], "common name": "propyltriethoxysilane", "id": 836},
  "NH4OH": {"class(es)": ["None"], "common name": "ammonium hydroxide", "id": 837},
  "hydrofluoric acid": {"class(es)": ["F"], "common name": "hydrofluoric acid", "id": 838},
  "cupric sulfate": {"class(es)": ["Cu"], "common name": "copper(II) sulfate", "id": 839},
  "magadiite": {"class(es)": ["Si"], "common name": "magadiite", "id": 840},
  "Mn(CH3COO)2*4H2O": {"class(es)": ["Mn"], "common name": "manganese(II) acetate tetrahydrate", "id": 841},
  "VOSO4*4H2O": {"class(es)": ["V"], "common name": "vanadyl sulfate tetrahydrate", "id": 842},
  "Colloidal silica": {"class(es)": ["Si"], "common name": "colloidal silica", "id": 843},
  "LiOH*H2O": {"class(es)": ["Li", "OH"], "common name": "lithium hydroxide monohydrate", "id": 844},
  "Aerosil 380": {"class(es)": ["Si"], "common name": "fumed silica", "id": 845},
  "NaAlO": {"class(es)": ["Al", "Na"], "common name": "sodium aluminate", "id": 846},
  "NH4-Y": {"class(es)": ["Si", "Al"], "common name": "ammonium Y zeolite", "id": 847},
  "silica solution ": {"class(es)": ["Si"], "common name": "silica solution", "id": 848},
  "Fumed silica": {"class(es)": ["Si"], "common name": "fumed silica", "id": 849},
  "APTES": {"class(es)": ["Si"], "common name": "(3-Aminopropyl)triethoxysilane", "id": 850},
  "aerosil 200": {"class(es)": ["Si"], "common name": "fumed silica", "id": 851},
  "gallium trioxide": {"class(es)": ["Ga"], "common name": "gallium(III) oxide", "id": 852},
  "TiF4": {"class(es)": ["Ti"], "common name": "titanium(IV) fluoride", "id": 853},
  "zinc chloride": {"class(es)": ["Zn"], "common name": "zinc chloride", "id": 854},
  "zinc(II) acetate": {"class(es)": ["Zn"], "common name": "zinc acetate", "id": 855},
  "Sr(NO3)2": {"class(es)": ["Sr"], "common name": "strontium nitrate", "id": 856},
  "n-butanol": {"class(es)": ["None"], "common name": "n-butanol", "id": 857},
  "Na2CO3": {"class(es)": ["Na"], "common name": "sodium carbonate", "id": 858},
  "kaolin": {"class(es)": ["Si", "Al"], "common name": "kaolin", "id": 859},
  "sodium fluoride": {"class(es)": ["Na", "F"], "common name": "sodium fluoride", "id": 860},
  "TIOPT": {"class(es)": ["Ti"], "common name": "titanium isopropoxide", "id": 861},
  "triglycol": {"class(es)": ["None"], "common name": "triglycol", "id": 862},
  "niobium ethoxide": {"class(es)": ["Nb"], "common name": "niobium ethoxide", "id": 863},
  "sodium tetraborate decahydrate": {"class(es)": ["B", "Na"], "common name": "sodium tetraborate decahydrate", "id": 864},
  "HSZ-320NAA": {"class(es)": ["Si", "Al"], "common name": "zeolite HSZ-320NAA", "id": 865},
  "grace silica gel": {"class(es)": ["Si"], "common name": "silica gel", "id": 866},
  "Ni(NO3)2": {"class(es)": ["Ni"], "common name": "nickel(II) nitrate", "id": 867},
  "indium nitrate": {"class(es)": ["In"], "common name": "indium(III) nitrate", "id": 868},
  "cabosil M7D": {"class(es)": ["Si"], "common name": "fumed silica", "id": 869},
  "aluminum 2-propanol": {"class(es)": ["Al"], "common name": "aluminum isopropanol", "id": 870},
  "RbCl": {"class(es)": ["Rb"], "common name": "rubidium chloride", "id": 871},
}